services: docker

install:
  docker build -t mongo-manager .

env:
  - test=unit
  - test=api
  - test=cmd

script:
  case $test in
  unit)
    docker run -t --tmpfs /db:exec --init mongo-manager rspec spec/mongo_manager
    ;;
  api)
    docker run -t --tmpfs /db:exec --init mongo-manager rspec spec/integration/api
    ;;
  cmd)
    docker run -t --tmpfs /db:exec --init mongo-manager rspec spec/integration/cmd
    ;;
  esac
