services: docker

install:
  docker build -t mongo-manager .

env:
  - test=unit
  - test=api
  - test=cmd

script:
  case $test in
  unit)
    docker run -t mongo-manager --tmpfs /db:exec --init rspec spec/mongo_manager
    ;;
  api)
    docker run -t mongo-manager --tmpfs /db:exec --init rspec spec/integration/init_spec.rb
    ;;
  cmd)
    docker run -t mongo-manager --tmpfs /db:exec --init rspec spec/integration/cmd_init_spec.rb
    ;;
  esac
