services: docker

install:
  docker build -t mongo-manager .

env:
  - test=unit
  - test=api
  - test=cmd

script:
  case $test in
  unit)
    rake test:unit
    ;;
  api)
    rake test:api
    ;;
  cmd)
    rake test:cmd
    ;;
  esac
